# Generated by Django 2.2.10 on 2021-06-28 17:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='static/default.png', null=True, upload_to='profile_pic/CustomerProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='static/default.png', null=True, upload_to='profile_pic/DistribuidorProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('product_image', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_image/')),
                ('codigo_fabrica', models.CharField(max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=300)),
                ('garantia', models.CharField(max_length=50, null=True)),
                ('marca', models.CharField(max_length=40)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Oferta', 'Oferta'), ('Disponible', 'Disponible'), ('Agotado', 'Agotado')], max_length=50, null=True)),
                ('product_precio_discuento', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)])),
                ('direccion', models.CharField(max_length=40)),
                ('proveedor_nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_details', models.CharField(max_length=255)),
                ('is_active', models.IntegerField(default=1)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Proveedor'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Orden Confirmada', 'Orden Confirmada'), ('Fuera para entregar', 'Fuera para entregar'), ('Entregada', 'Entregada')], max_length=50, null=True)),
                ('delivery_zona', models.CharField(max_length=40)),
                ('distrito', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=9)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Customer')),
                ('distribuidor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Distribuidor')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('ingreso', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('salida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dia', models.DateField(auto_now_add=True, null=True)),
                ('hora', models.TimeField(auto_now_add=True, null=True)),
                ('producto_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('feedback', models.CharField(max_length=500)),
                ('tipo', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('descripcion_solucion', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerEmpresarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=80)),
                ('razonsocial', models.CharField(max_length=300)),
                ('estado', models.CharField(max_length=20)),
                ('condicion', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('distrito', models.CharField(max_length=20)),
                ('ubigeo', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
