# Generated by Django 3.0.5 on 2021-04-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_personalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('dark', 'dark'), ('light', 'light')], max_length=20),
        ),
    ]
