# Generated by Django 3.0.5 on 2021-04-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20210422_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalizacion',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
