# Generated by Django 2.2.10 on 2021-04-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20210424_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='distribuidor',
        ),
    ]
