# Generated by Django 2.2.10 on 2021-04-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('ecom', '0008_orders_distribuidor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='distribuidor',
        ),
        migrations.AddField(
            model_name='orders',
            name='distribuidor',
            field=models.ManyToManyField(null=True, to='auth.Group'),
        ),
    ]
