# Generated by Django 2.2.10 on 2021-05-01 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0009_auto_20210427_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='distribuidor',
        ),
        migrations.AddField(
            model_name='orders',
            name='distribuidor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
