# Generated by Django 2.2.10 on 2021-05-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20210430_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='distrito',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='dni',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
