# Generated by Django 2.2.10 on 2021-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_auto_20210513_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo_fabrica',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='garantia',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
