# Generated by Django 3.2.4 on 2021-07-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_payment'),
        ('ecom', '0015_distribuidor'),
    ]

    operations = [
    ]
